# Generated by Django 3.2.25 on 2024-06-05 23:08

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_mvp', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourperweek', models.IntegerField()),
                ('studentnumber', models.IntegerField()),
                ('agerange', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_9', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('is_published', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.school')),
            ],
        ),
    ]
