# Generated by Django 3.2.25 on 2024-06-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlines', '0001_initial'),
        ('listings', '0002_auto_20240613_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline',
        ),
        migrations.AlterField(
            model_name='listing',
            name='headline',
            field=models.ManyToManyField(blank=True, related_name='listings', to='headlines.Headline'),
        ),
    ]
