# Generated by Django 3.2.25 on 2024-08-12 20:06

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to),
        ),
    ]
