# Generated by Django 3.2.25 on 2024-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlines', '0002_headline_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='name',
            field=models.CharField(default='headlines_pics', max_length=200),
        ),
    ]
