# Generated by Django 3.2.25 on 2024-06-05 23:08

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_mvp', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('photo_9', models.ImageField(blank=True, null=True, upload_to=utils.utils.photo_upload_to)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
