# Generated by Django 3.2.25 on 2024-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
